import Head from 'next/head'
import { useState, useEffect } from 'react'
import axios from 'axios'


export default function Home() {
  const [data, SetData] = useState("")
  const [getdata, SetgetData] = useState([])
  useEffect(() => { getData() }, [])
  const getData = () => {
    axios
      .post("/api/get_Task")
      .then((response) => {
        console.log(response.data.data)
        SetgetData(response.data.data)
      })
      .catch((err) => console.log(err))
  }
  const handleSubmit = () => {
    axios
      .post("/api/set_Task", { task: data })
      .then((response) => {
        console.log(response.data)
        getData()
      })
      .catch((err) => console.log(err))
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <input onChange={(e) => SetData(e.target.value)} />
        <button onClick={() => handleSubmit()}>submit</button>
        <ul>
          {getdata?.map((item) => <li key={item._id}>{item.task}</li>)}
          
        </ul>
      </main>
    </>
  )
}
